require 'openssl'
require 'pry'
require 'nokogiri'
require 'open-uri'
require 'colorize'
require 'strings/extensions'

require_relative '../lib/balboa_park_itinerary_ideas/version'
require_relative '../lib/balboa_park_itinerary_ideas/cli'
require_relative '../lib/balboa_park_itinerary_ideas/scraper'
require_relative '../lib/balboa_park_itinerary_ideas/itinerary'
